name: Deploy to Cloud Run (Docker)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy FastAPI (Docker)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: cvoapi
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Authenticate with Service Account
        run: |
          echo '${{ secrets.GCP_CREDENTIALS }}' > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud config set project cvoapi

      - name: Configure Docker for Google Artifact Registry
        run: gcloud auth configure-docker --quiet

      - name: Build Docker image
        run: docker build -t gcr.io/cvoapi/fastapi-app .

      - name: Push Docker image
        run: docker push gcr.io/cvoapi/fastapi-app
# ...existing code...
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy langdetect \
            --image gcr.io/cvoapi/fastapi-app \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --memory 4Gi

      - name: Set IAM Policy to allow public access
        run: |
          gcloud run services add-iam-policy-binding langdetect \
            --region=us-central1 \
            --member="allUsers" \
            --role="roles/run.invoker"

      - name: Display Cloud Run Service URL
        run: |
          echo "Cloud Run Service URL:"
          gcloud run services describe langdetect \
            --region=us-central1 \
            --format='value(status.url)'
# ...existing code...

      - name: Cleanup credentials
        run: rm -f key.json || true